### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by janblim**
changed get all reviews so that preview image is coming from the SpotImage table.

- removed previewImage column from Spotmage table
- added code to add spotimage to get all bookings for a spot route AND get all reviews of current user

### CODE REVIEW

**Review by AnthonyBronca — APPROVED** [review]

**Comment by janblim** [comment]
finished all routes

**Comment by janblim** [comment]
ok

**Comment by janblim** [comment]
ok

**Comment by janblim** [comment]
ok

**Comment by janblim** [comment]
ok

**Comment by janblim** [comment]
ok

**Pull request merged**
